
all:
	g++ -std=gnu++11 ejercicio.hpp -ggdb -o salida
	g++ -std=gnu++11 ejercicio1.cpp ejercicio.hpp -ggdb -o ejercicio1
	g++ -std=gnu++11 -g ejercicio1_0.cpp ejercicio.hpp -ggdb -o ejercicio1_0
	g++ -std=gnu++11 ejercicio2.cpp ejercicio.hpp -ggdb -o ejercicio2
	g++ -std=gnu++11 ejercicio3.cpp ejercicio.hpp -ggdb -o ejercicio3
	g++ -std=gnu++11 ejercicio4.cpp ejercicio.hpp -ggdb -o ejercicio4

ejercicio1:
	g++ -std=gnu++11 ejercicio1.cpp ejercicio.hpp -ggdb -o ejercicio1

ejercicio1_0:
	g++ -std=gnu++11 -g ejercicio1_0.cpp ejercicio.hpp -ggdb -o ejercicio1_0

ejercicio2:
	g++ -std=gnu++11 ejercicio2.cpp ejercicio.hpp -ggdb -o ejercicio2

ejercicio3:
	g++ -std=gnu++11 ejercicio3.cpp ejercicio.hpp -ggdb -o ejercicio3

ejercicio4:
	g++ -std=gnu++11 ejercicio4.cpp ejercicio.hpp -ggdb -o ejercicio4

clean:
	rm -f salida ejercicio1 ejercicio2 ejercicio3 ejercicio4 ejercicio1_0
